- name: copy CAsigned files ca.crt server.cert back to openvpnserver
  hosts: openvpnserver
  become: yes
  become_user: openvpn
  tasks:
    - name: ping
      action: ping #apt: name=python state=installed

    - name: create directory in openvpn for clients
      become: true
      become_user: openvpn
      file:
        path: ~/client-configs/keys
        state: directory
        mode: '0700'

    - name: add data to file vars
      blockinfile:
        path: /opt/EasyRSA-3.0.4/vars
        block: |
          set_var EASYRSA_REQ_COUNTRY    "IND"
          set_var EASYRSA_REQ_PROVINCE   "Telangana"
          set_var EASYRSA_REQ_CITY       "Hyderabad"
          set_var EASYRSA_REQ_ORG        "digitaldots.ai"
          set_var EASYRSA_REQ_EMAIL      "sathish@digitaldots.ai"
          set_var EASYRSA_REQ_OU         "DigitalDots"
          set_var EASYRSA_REQ_CN         "sathish"
          set_var EASYRSA_BATCH           "15"

    - name: gen-req client
      command: /opt/EasyRSA-3.0.4/easyrsa gen-req sathish nopass
      args:
        chdir: /opt/EasyRSA-3.0.4/

    - name: copy pki/private/sathish.key ~/client-configs/keys/
      copy:
        src: /opt/EasyRSA-3.0.4/pki/private/sathish.key
        dest: ~/client-configs/keys/
        remote_src: yes

    - name: copy private sathish.req to openvpn /tmp local
      fetch:
        src: /opt/EasyRSA-3.0.4/pki/reqs/sathish.req
        dest: /tmp/
        flat: yes

- name: copy file to CA server
  hosts: openvpnca
  become: yes
  become_user: openvpn
  tasks:
    - name: ping
      action: ping #apt: name=python state=installed

    - name: copy from /tmp to CA remote server
      become: true
      become_user: openvpn
      copy:
        src: /tmp/sathish.req
        dest: /tmp/

    - name: import-request client
      command: /opt/EasyRSA-3.0.4/easyrsa import-req /tmp/sathish.req sathish
      args:
        chdir: /opt/EasyRSA-3.0.4/

    - name: sign-req sathish
      command: /opt/EasyRSA-3.0.4/easyrsa sign-req client sathish
      args:
        chdir: /opt/EasyRSA-3.0.4/

    - name: delete file after copy from /tmp to CA remote server
      file:
        path: /tmp/sathish.req
        state: absent

    - name: delay
      command: sleep 2

    - name: copy private sathish.crt from CAserver to local
      become: true
      become_user: openvpn
      fetch:
        src: /opt/EasyRSA-3.0.4/pki/issued/sathish.crt
        dest: /tmp/   #doubt
        remote_src: yes
        flat: yes

- name: copy CAsigned files /tmp/sathish.crt ~/client-configs/keys/
  hosts: openvpnserver
  become: true
  become_user: openvpn
  tasks:
    - name: ping
      action: ping #apt: name=python state=installed

    - name: copy CAsigned files /tmp/sathish.crt ~/client-configs/keys/
      copy:
        src: /tmp/sathish.crt
        dest: ~/client-configs/keys/


#    - name: copy ~/EasyRSA-3.0.4/ta.key ~/client-configs/keys/
#      copy:
#        src: /opt/EasyRSA-3.0.4/ta.key
#        dest: ~/client-configs/keys/
#        remote_src: yes

#    - name: sudo cp /etc/openvpn/ca.crt ~/client-configs/keys/
#      become_user: ubuntu
#      become: true
#      copy:
#        src: /etc/openvpn/ca.crt
#        dest: ~/client-configs/keys/
#        remote_src: yes

    - name: copy /usr/share/doc/openvpn/examples/sample-config-files/client.conf ~/client-configs/base.conf
      become: true
      become_user: openvpn
      copy:
        src: /usr/share/doc/openvpn/examples/sample-config-files/client.conf
        dest: ~/client-configs/base.conf
        remote_src: yes

    - name: Replace ~/client-configs/base.conf
      become_user: openvpn
      lineinfile:
        path: ~/client-configs/base.conf
        regexp: '^remote my-server-1 1194'
        line: remote 13.56.77.196 443
        mode: '0644'

    - name: Replace ;proto tcp
      become_user: openvpn
      lineinfile:
        path: ~/client-configs/base.conf
        regexp: '^proto udp'
        line: proto tcp
        mode: '0644'

    - name: Replace user nobody
      become_user: openvpn
      lineinfile:
        path: ~/client-configs/base.conf
        regexp: '^;user nobody'
        line: user nobody
        mode: '0644'

    - name: Replace group nogroup
      become_user: openvpn
      lineinfile:
        path: ~/client-configs/base.conf
        regexp: '^;group nogroup'
        line: group nogroup


    - name: Replace ca.crt
      become_user: openvpn
      lineinfile:
        path: ~/client-configs/base.conf
        regexp: '^ca ca.crt'
        line: ;ca ca.crt


    - name: Replace cert client.crt
      become_user: openvpn
      lineinfile:
        path: ~/client-configs/base.conf
        regexp: '^cert client.crt'
        line: ;cert client.crt


    - name: Replace key client.key
      become_user: openvpn
      lineinfile:
        path: ~/client-configs/base.conf
        regexp: '^key client.key'
        line: ;key client.key

    - name: Replace key client.key
      become_user: openvpn
      lineinfile:
        path: ~/client-configs/base.conf
        regexp: '^tls-auth ta.key 1'
        line: ;tls-auth ta.key 1


    - name: add data to file vars
      blockinfile:
        path: ~/client-configs/base.conf
        insertafter: "cipher AES-256-CBC"
        block: |
          auth SHA256
          key-direction 1
          ; script-security 2
          ; up /etc/openvpn/update-resolv-conf
          ; down /etc/openvpn/update-resolv-conf
          ; script-security 2
          ; up /etc/openvpn/update-systemd-resolved
          ; down /etc/openvpn/update-systemd-resolved
          ; down-pre
          ; dhcp-option DOMAIN-ROUTE .

    - name: ~/client-configs/make_config.sh
      blockinfile:
        path: ~/client-configs/make_config.sh
        block: |
          # First argument: Client identifier
          KEY_DIR=~/client-configs/keys
          OUTPUT_DIR=~/client-configs/files
          BASE_CONFIG=~/client-configs/base.conf
          cat ${BASE_CONFIG} <(echo -e '<ca>') \
          ${KEY_DIR}/ca.crt <(echo -e '</ca>\n<cert>') \
          ${KEY_DIR}/${1}.crt <(echo -e '</cert>\n<key>') \
          ${KEY_DIR}/${1}.key <(echo -e '</key>\n<tls-auth>') \
          ${KEY_DIR}/ta.key <(echo -e '</tls-auth>') > ${OUTPUT_DIR}/${1}.ovpn


    - name: make ovpem file
      become: true
      become_user: openvpn
      command: '/home/openvpn/client-configs/make_config.sh sathish'
