---
- name: Server and CA initial setup for openvpn
  hosts: openvpnca,openvpnserver
  become: yes
  become_user: root
  tasks:
    - name: ping
      action: ping #apt: name=python state=installed
    - name: add user
      command: adduser openvpn
    - name: granting admin previlage
      command: usermod -aG sudo openvpn
    - name: ufw add OpenSSH
      command: ufw allow OpenSSH
    - name: ufw enable
      command: ufw enable
    - name: sync ssh from root
      command: rsync --archive --chown=openvpn:openvpn ~/.ssh /home/openvpn