---
- name: configure files
  hosts: openvpnca
  become: yes
  become_user: openvpn
  tasks:
    - name: ping
      action: ping #apt: name=python state=installed
    - name: create config file
      become: true
      become_user: openvpn
      copy:
        src: /opt/EasyRSA-3.0.4/vars.example
        dest: /opt/EasyRSA-3.0.4/vars
        remote_src: yes
        mode: '0644'
    - name: add data to file vars
      blockinfile:
        path: /opt/EasyRSA-3.0.4/vars
        block: |
          set_var EASYRSA_REQ_COUNTRY    "IND"
          set_var EASYRSA_REQ_PROVINCE   "Telangana"
          set_var EASYRSA_REQ_CITY       "Hyderabad"
          set_var EASYRSA_REQ_ORG        "digitaldots.ai"
          set_var EASYRSA_REQ_EMAIL      "sasidharp@digitaldots.ai"
          set_var EASYRSA_REQ_OU         "DigitalDots"
          set_var EASYRSA_REQ_CN         "Easy-RSA CA"
          set_var EASYRSA_BATCH           "15"

    - name: run init-pki
      command: /opt/EasyRSA-3.0.4/easyrsa init-pki
      args:
        chdir: /opt/EasyRSA-3.0.4/
    - name: build-ca nopss
      command: /opt/EasyRSA-3.0.4/easyrsa build-ca nopass
      args:
        chdir: /opt/EasyRSA-3.0.4/


- name: configure files openvpn server
  hosts: openvpnserver
  become: yes
  become_user: openvpn
  tasks:
    - name: ping
      action: ping
    - name: create config file
      copy:
        src: /opt/EasyRSA-3.0.4/vars.example
        dest: /opt/EasyRSA-3.0.4/vars
        remote_src: yes
        mode: '0644'
    - name: add data to file vars
      blockinfile:
        path: /opt/EasyRSA-3.0.4/vars
        block: |
          set_var EASYRSA_REQ_COUNTRY    "IND"
          set_var EASYRSA_REQ_PROVINCE   "Telangana"
          set_var EASYRSA_REQ_CITY       "Hyderabad"
          set_var EASYRSA_REQ_ORG        "digitaldots.ai"
          set_var EASYRSA_REQ_EMAIL      "sasidharp@digitaldots.ai"
          set_var EASYRSA_REQ_OU         "DigitalDots"
          set_var EASYRSA_REQ_CN         "server"
          set_var EASYRSA_BATCH           "15"

    - name: run init-pki
      command: /opt/EasyRSA-3.0.4/easyrsa init-pki
      args:
        chdir: /opt/EasyRSA-3.0.4/

    - name: gen-req server
      command: /opt/EasyRSA-3.0.4/easyrsa gen-req server nopass
      args:
        chdir: /opt/EasyRSA-3.0.4/

    - name: copy private key to openvpn /etc/openvpn/
      become: true
      become_user: root
      copy:
        src: /opt/EasyRSA-3.0.4/pki/private/server.key
        dest: /etc/openvpn/
        remote_src: yes
        mode: '0644'

    - name: copy private server.req to openvpn /tmp local
      fetch:
        src: /opt/EasyRSA-3.0.4/pki/reqs/server.req
        dest: /tmp/
        flat: yes

- name: copy file to CA server
  hosts: openvpnca
  become: yes
  become_user: openvpn
  tasks:
    - name: ping
      action: ping

    - name: copy from /tmp to CA remote server
      copy:
        src: /tmp/server.req
        dest: /tmp/

    - name: import-request
      command: /opt/EasyRSA-3.0.4/easyrsa import-req /tmp/server.req server
      args:
        chdir: /opt/EasyRSA-3.0.4/

    - name: sign-req server
      command: /opt/EasyRSA-3.0.4/easyrsa sign-req server server
      args:
        chdir: /opt/EasyRSA-3.0.4/

    - name: delete file after copy from /tmp to CA remote server
      file:
        path: /tmp/server.req
        state: absent

    - name: delay
      command: sleep 2

    - name: copy private server.crt from CAserver to local
      fetch:
        src: /opt/EasyRSA-3.0.4/pki/issued/server.crt
        dest: /tmp/
        remote_src: yes
        flat: yes

    - name: copy ca.crt from CAserver to local
      fetch:
        src: /opt/EasyRSA-3.0.4/pki/ca.crt
        dest: /tmp/
        remote_src: yes
        flat: yes

- name: copy CAsigned files ca.crt server.cert back to openvpnserver
  hosts: openvpnserver
  become: yes
  become_user: openvpn
  tasks:
    - name: ping
      action: ping #apt: name=python state=installed

    - name: copy from /tmp/ to /etc/openvpn/ remote server
      copy:
        src: /tmp/{server.crt,ca.crt}
        dest: /etc/openvpn/

    - name: gen-dh server
      command: /opt/EasyRSA-3.0.4/easyrsa gen-dh
      args:
        chdir: /opt/EasyRSA-3.0.4/

    - name: genkey server
      command: openvpn --genkey --secret ta.key
      args:
        chdir: /opt/EasyRSA-3.0.4/

    - name: copy /EasyRSA-3.0.4/ta.key to /etc/openvpn/
      copy:
        src: /opt/EasyRSA-3.0.4/ta.key
        dest: /etc/openvpn/
        remote_src: yes


    - name: copy /EasyRSA-3.0.4/pki/dh.pem /etc/openvpn/
      copy:
        src: /opt/EasyRSA-3.0.4/pki/dh.pem
        dest: /etc/openvpn/
        remote_src: yes

    - name: copy server.conf from present directory to /etc/openvpn/
      copy:
        src: ./server.conf
        dest: /etc/openvpn/

    - name: enable net.ipv4.ip_forward=1 in /etc/sysctl.conf
      become: true
      become_user: root
      lineinfile:
        path: /etc/sysctl.conf
        line: net.ipv4.ip_forward=1

    - name: sudo sysctl -p
      become: true
      command: sysctl -p

    - name: ipv4 |grep
      become: true
      shell: ip route | awk '/default/ {print $5}' #ip route | grep default
      register: pinterface
    - debug:
        var: pinterface.stdout

    - name: add data to file vars
      become: true
      become_user: root
      blockinfile:
        path: /etc/ufw/before.rules
        insertafter: "#   ufw-before-forward"
        block: |
          # START OPENVPN RULES
          # NAT table rules
          *nat
          :POSTROUTING ACCEPT [0:0]
          # Allow traffic from OpenVPN client to wlp11s0 (change to the interface you discovered!)
          -A POSTROUTING -s 10.8.0.0/8 -o {{pinterface.stdout}} -j MASQUERADE
          COMMIT
          # END OPENVPN RULES

    - name: Replace DEFAULT_FORWARD_POLICY="DROP" to DEFAULT_FORWARD_POLICY="ACCEPT"
      become_user: root
      lineinfile:
        path: /etc/default/ufw
        regexp: '^DEFAULT_FORWARD_POLICY="DROP"'
        line: DEFAULT_FORWARD_POLICY="ACCEPT"
        mode: '0644'

    - name: ufw allow 443/tcp
      become: true
      become_user: root
      command: ufw allow 443/tcp

    - name: ufw allow OpenSSH
      become: true
      become_user: root
      command: ufw allow OpenSSH

    - name: ufw disable
      become: true
      become_user: root
      command: ufw disable

    - name: ufw enable
      become: true
      become_user: root
      command: ufw enable

    - name: systemctl start openvpn@server
      become: true
      become_user: root
      command: systemctl start openvpn@server

    - name: systemctl status openvpn@server
      become: true
      become_user: root
      command: systemctl status openvpn@server

    - name: ip addr show tun0
      become: true
      become_user: root
      command: ip addr show tun0

    - name: systemctl enable openvpn@server
      become: true
      become_user: root
      command: systemctl enable openvpn@server